### ISSUE TITLE
[BUG] March is spelled wrong

### ISSUE THREAD

**Issue by MichaelZhao21** [tams-cso/tams-club-cal#560]
### Describe the bug

The word "March" is spelled wrong in the changelog on the [About page](https://tams.club/about).

### To Reproduce

1. Go to the about page
2. Scroll down to the bottom of the changelog (see screenshot below)
3. See error

### Expected behavior

Should be spelled right lol

### Screenshots or Links

![image](https://user-images.githubusercontent.com/37679458/204111575-248d4cad-944a-4aab-a712-6410247da84b.png)

### Environment

N/A

### Additional context

Check `data.json` for the text content.

**Comment by jinitsuga** [comment]
Hi, I can take care of this!

**Comment by MichaelZhao21** [comment]
@jinitsuga any updates on this?

**Comment by MichaelZhao21** [comment]
Closed by #566
